# Generated by Django 3.1.7 on 2021-03-24 05:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_faculty_facultycourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_title', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
            ],
        ),
        migrations.RemoveField(
            model_name='facultycourse',
            name='year',
        ),
        migrations.AddField(
            model_name='facultycourse',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facultycourse',
            name='course_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.course'),
        ),
    ]
