# Generated by Django 3.1.7 on 2021-03-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210324_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coe',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Coe',
            },
        ),
    ]
