# Generated by Django 3.1.7 on 2021-05-10 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_event_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grace_marks',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
