# Generated by Django 3.1.7 on 2021-05-13 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210510_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='fromA',
            field=models.IntegerField(default=85, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='toB',
            field=models.IntegerField(default=84, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
