# Generated by Django 3.1.7 on 2021-05-13 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_student_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grace_marks',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
