# Generated by Django 3.1.7 on 2021-05-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210513_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='coe',
            name='grace_mark_applied',
            field=models.BooleanField(default=False),
        ),
    ]
