# Generated by Django 3.1.7 on 2021-06-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_coe_grace_mark_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoolCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(default=1)),
                ('grace_mark_applied', models.BooleanField(default=False)),
            ],
        ),
    ]
